//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageProg.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagClient
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDTag { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
